model_config:
  concat_vl:
    num_classes: 2
    dropout: 0.1
    image_encoder:
      type: resnet152
      params:
        pretrained: true
        pool_type: avg
        num_output_features: 1
    image_mapper:
      params:
        in_features: 2048
        out_features: 32
    text_encoder:
      params:
        module: linear
        in_dim: 300
        out_dim: 32
    fusion:
      params:
        # Visual Dim (32) + Text Dim (32)
        # Follow the API of nn.Linear
        in_features: 64
        out_features: 512
    losses:
    - cross_entropy
    classifier:
      type: mlp
      params:
        in_dim: 512
        out_dim: ${model_config.concat_vl.num_classes}
        num_layers: 0
